### ISSUE TITLE
JetBrains Mono is a hardcoded font in the QMLTermWidget element.

### ISSUE THREAD

**Issue by omaemae** [cyberos/cyber-terminal#1]
Since I don't know how to pull the font from the Settings daemon/MeuiKit (and am too lazy to make a DBus handler), I hardcoded the font to `JetBrains Mono` for now (since that's the monospace font that I use). Obviously this isn't ideal.

@rekols Could you help me out with this?

**Comment by rekols** [comment]
of course.
