### ISSUE TITLE
Text drifts away because of irregular Unicode characters.

### ISSUE THREAD

**Issue by omaemae** [cyberos/cyber-terminal#3]
I'm not sure if this is a Cyber Terminal issue or a QMLTermWidget issue, but the text drifts away when paired with Unicode characters.

Tested with:
 - JetBrains Mono
 - Noto Sans Mono
 - bashtop
 - vtop

![image](https://user-images.githubusercontent.com/17727163/102972831-fa321b80-44fb-11eb-89d5-e00b5c02c3c3.png)
![image](https://user-images.githubusercontent.com/17727163/102972842-03bb8380-44fc-11eb-9ecb-08ce6cffadb2.png)
![image](https://user-images.githubusercontent.com/17727163/102972885-146bf980-44fc-11eb-9c7f-642de3bac04e.png)
![image](https://user-images.githubusercontent.com/17727163/102972915-2352ac00-44fc-11eb-87e3-6c22331b9849.png)

Todo:
 - [ ] Check if this issue occurs on cool-retro-term
 - [ ] Check if we can fix this issue by deriving code from cool-retro-term

**Comment by omaemae** [comment]
Haha, I can't even launch cool-retro-term.
```sh
$ cool-retro-term
default KB_LAYOUT_DIR:  "/usr/lib/qt/qml/QMLTermWidget/kb-layouts"
QObject::connect: No such slot Konsole::TerminalDisplay_QML_58::close()
loadAllColorSchemes
WARNING: Cannot find style "meui-style" - fallback: "/usr/lib/qt/qml/QtQuick/Controls/Styles/Desktop"
qrc:/BurnInEffect.qml:67:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/BurnInEffect.qml:59:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/BurnInEffect.qml:54:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/qt/qml/QMLTermWidget/QMLTermScrollbar.qml:29:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/PreprocessedTerminal.qml:62:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/PreprocessedTerminal.qml:57:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/PreprocessedTerminal.qml:51:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/PreprocessedTerminal.qml:47:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[1]    197118 segmentation fault (core dumped)  cool-retro-term
```

**Comment by omaemae** [comment]
This seems to happen in other QMLTermWidget apps as well (tested with [Hawaii Terminal](https://github.com/hawaii-desktop/hawaii-terminal), albeit somewhat broken):

![image](https://user-images.githubusercontent.com/17727163/102974007-15058f80-44fe-11eb-9e53-fbc1174a2365.png)

**Comment by rekols** [comment]
Seems to be an issue of QMLTermWidget?

**Comment by omaemae** [comment]
Yup. No idea how to fix it, leaving it as is.
