### ISSUE TITLE
qrc:/qml/main.qml:5:1: module "org.cyber.QMLTermWidget" is not installed

### ISSUE THREAD

**Issue by Z-bin** [cyberos/cyber-terminal#5]
Development environment： Linux kylin 5.10.3-arch1-1 #1 SMP PREEMPT Sun, 27 Dec 2020 10:50:46 +0000 x86_64 GNU/Linux
Qt version: 5.15.2

cyber-terminal's log: [cyber-terminal](https://github.com/cyberos/cyber-terminal/commit/bca46108fd68dfc1fb919cbd59ca68aaf5741e62)
meuikit‘s log: [meuikit](https://github.com/cyberos/meuikit/commit/31859f26c7f79b842fc613c4958fd64753fdc055)
--
Compilation was successful but an error was reported when running
`QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:5:1: module "org.cyber.QMLTermWidget" is not installed
`

**Comment by omaemae** [comment]
Please check the new build instructions, hopefully that will solve the issue!

**Comment by Z-bin** [comment]
> Please check the new build instructions, hopefully that will solve the issue!

Thank you very much for your enthusiastic answer～ 
I have solved this problem.
